version: '3.8'
 
services:
  mysql-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-container
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mydata:/var/lib/mysql
 
  tourplanservice:
    image: snahammed/tourplanimage:latest
    container_name: tourplanservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/tourplanservicedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8090
    ports:
      - "8090:8090"
    networks:
      - mynetwork
 
  placeservice:
    image: snahammed/placeimage:latest
    container_name: placeservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/placeservicedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8070
    ports:
      - "8070:8070"
    networks:
      - mynetwork
 
  userservice:
    image: snahammed/userimage:latest
    container_name: userservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/userservicedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8099
    ports:
      - "8099:8099"
    networks:
      - mynetwork
 
  feedbackservice:
    image: snahammed/feedbackimage:latest
    container_name: feedbackservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/feedbackservicedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8060
    ports:
      - "8060:8060"
    networks:
      - mynetwork
 
  adminservice:
    image: snahammed/adminimage:latest
    container_name: adminservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/adminservicedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8085
    ports:
      - "8085:8085"
    networks:
      - mynetwork
 
  serverservice:
    image: snahammed/serverimage:latest
    container_name: serverservice
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    networks:
      - mynetwork
 
networks:
  mynetwork:
    driver: bridge
 
volumes:
  mydata:
