version: '3.8'

services:
  tourplanservice-mysql:
    image: mysql
    container_name: tourplanservice-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tourplanservicedb
    volumes:
      - tourplanservice-mysql-db:/var/lib/mysql
    networks:
      - mynetwork
  
  placeservice-mysql:
    image: mysql
    container_name: placeservice-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=placeservicedb
    volumes:
      - placeservice-mysql-db:/var/lib/mysql
    networks:
      - mynetwork
   

  userservice-mysql:
    image: mysql
    container_name: userservice-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userservicedb
    volumes:
      - userservice-mysql-db:/var/lib/mysql
    networks:
      - mynetwork
    

  feedbackservice-mysql:
    image: mysql
    container_name: feedbackservice-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=feedbackservicedb
    volumes:
      - feedbackservice-mysql-db:/var/lib/mysql
    networks:
      - mynetwork
  

  adminservice-mysql:
    image: mysql
    container_name: adminservice-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=adminservicedb
    volumes:
      - adminservice-mysql-db:/var/lib/mysql
    networks:
      - mynetwork
   

  tourplanservice:
    image: shalemraj/tourplanimage
    container_name: tourplanservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://tourplanservice-mysql:3306/tourplanservicedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8090
    ports:
      - "8090:8090"
    networks:
      - desktop_sonarnet
    command:
      mvn clean verify sonar:sonar -Dsonar.host.url=http://sonarqube:9001 _Dsonar.projectKey=tourplan


  placeservice:
    image: shalemraj/placeimage
    container_name: placeservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://placeservice-mysql:3306/placeservicedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8070
    ports:
      - "8070:8070"
    networks:
      - desktop_sonarnet
    command:
      mvn clean verify sonar:sonar -Dsonar.host.url=http://sonarqube:9001 _Dsonar.projectKey=place


  userservice:
    image: shalemraj/userimage
    container_name: userservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://userservice-mysql:3306/userservicedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8099
    ports:
      - "8099:8099"
    networks:
      - desktop_sonarnet
    command:
      mvn clean verify sonar:sonar -Dsonar.host.url=http://sonarqube:9001 _Dsonar.projectKey=user


  feedbackservice:
    image: shalemraj/feedbackimage
    container_name: feedbackservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://feedbackservice-mysql:3306/feedbackservicedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8060
    ports:
      - "8060:8060"
    networks:
      - desktop_sonarnet
    command:
      mvn clean verify sonar:sonar -Dsonar.host.url=http://sonarqube:9001 _Dsonar.projectKey=feedback


  adminservice:
    image: shalemraj/adminimage
    container_name: adminservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://adminservice-mysql:3306/adminservicedb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8085
    ports:
      - "8085:8085"
    networks:
      - desktop_sonarnet
    command:
      mvn clean verify sonar:sonar -Dsonar.host.url=http://sonarqube:9001 _Dsonar.projectKey=admin


  serverservice:
    image: shalemraj/serverimage
    container_name: serverservice
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    networks:
      - desktop_sonarnet

networks:
  mynetwork:
    driver: bridge
  desktop_sonarnet:  
    driver: bridge

volumes:
  tourplanservice-mysql-db:
  placeservice-mysql-db:
  userservice-mysql-db:
  feedbackservice-mysql-db:
  adminservice-mysql-db:
